# Generated by Django 5.0.2 on 2024-03-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TaskName', models.CharField(max_length=50, verbose_name='Название')),
                ('TaskDescription', models.TextField(verbose_name='Описание')),
                ('Task_key', models.CharField(max_length=50, verbose_name='Флаг')),
                ('Task_category', models.CharField(max_length=20, verbose_name='Категория')),
                ('Task_difficulty', models.CharField(max_length=20, verbose_name='Сложность')),
                ('Task_href', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['-id'],
            },
        ),
    ]
