# Generated by Django 5.0.2 on 2024-03-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='TaskDescription',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='TaskName',
            field=models.CharField(default='', max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='Task_category',
            field=models.CharField(choices=[('osint', 'OSINT'), ('reverse', 'Reverse'), ('web', 'Web'), ('crypto', 'Crypto'), ('other', 'Other')], default='', max_length=10, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='Task_difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('extreme', 'Extreme')], default='', max_length=10, verbose_name='Сложность'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='Task_key',
            field=models.CharField(default='web_hack3r{}', max_length=50, verbose_name='Флаг'),
        ),
    ]
