# Generated by Django 5.0.2 on 2024-03-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_tasks_taskdescription_alter_tasks_taskname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='Task_category',
            field=models.CharField(choices=[('Osint', 'Osint'), ('Reverse', 'Reverse'), ('Web', 'Web'), ('Crypto', 'Crypto'), ('Other', 'Other')], default='', max_length=10, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='Task_difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard'), ('Extreme', 'Extreme')], default='', max_length=10, verbose_name='Сложность'),
        ),
    ]
