# Generated by Django 5.0.2 on 2024-03-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_data',
            field=models.JSONField(default={'completed_tasks': []}),
        ),
    ]
