# Generated by Django 5.0.2 on 2024-03-16 15:57

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_customuser_user_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_data',
            field=models.JSONField(default=main.models.default_data),
        ),
    ]
